name: CI

on:
  push:
    branches:
      - master
      - development
    # Do not run on tags
    tags-ignore:
      - "*"
  pull_request:
    # Run on to branches with an open PR
    branches:
      - "*"

env:
  NODE_VERSION: 17

jobs:
  lint:
    name: ESLint / Prettiers / Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '{{ env.NODE_VERSION }}'

      - name: Code checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run format
        run: npm run format

      - name: Run tests
        run: npm run test:nowatch